apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.05
    profile: false

    max_hamming: 0
    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true        
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    tag:
      ids:    [1, 10]                   
      frames: ["tag36h11:1", "tag36h11:10"]
      sizes:  [0.05, 0.05]
